In [1]:
raw_data = [
    {"dt": "2026-01-17 10:00:01", "lvl": "INFO", "msg": "Login", "user": 101},
    {"dt": "2026-01-17 10:05:22", "lvl": "ERROR", "msg": "DB Error", "user": None}, # Brak usera!
    {"dt": "2026-01-17 10:07:01", "lvl": "INFO", "msg": "Upload", "user": 102},
    {"dt": "2026-01-18 08:00:00", "lvl": "ERROR", "msg": "Timeout", "user": 101},
    {"dt": "2026-01-18 09:15:00", "lvl": "INFO", "msg": "Login", "user": 105}
]

In [18]:
import pandas as pd

df = pd.DataFrame(raw_data)

df['dt'] = pd.to_datetime(df['dt'])

df['lvl'] = df['lvl'].astype("category")

display(df.head())
display(df.info())

number_of_na = sum(df['user'].isna())
number_of_na

df['user'].fillna(0, inplace=True)

display(df.head())

date_occurances = df['dt'].dt.date.value_counts()
print(date_occurances)

df_errors = df['lvl']
df_errors.to_csv("error.csv", index=False)

                   dt    lvl       msg   user
0 2026-01-17 10:00:01   INFO     Login  101.0
1 2026-01-17 10:05:22  ERROR  DB Error    NaN
2 2026-01-17 10:07:01   INFO    Upload  102.0
3 2026-01-18 08:00:00  ERROR   Timeout  101.0
4 2026-01-18 09:15:00   INFO     Login  105.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   dt      5 non-null      datetime64[ns]
 1   lvl     5 non-null      category
 2   msg     5 non-null      object
 3   user    4 non-null      float64
dtypes: category(1), datetime64[ns](1), float64(1), object(1)
memory usage: 381.0+ bytes

None

                   dt    lvl       msg   user
0 2026-01-17 10:00:01   INFO     Login  101.0
1 2026-01-17 10:05:22  ERROR  DB Error    0.0
2 2026-01-17 10:07:01   INFO    Upload  102.0
3 2026-01-18 08:00:00  ERROR   Timeout  101.0
4 2026-01-18 09:15:00   INFO     Login  105.0

dt
2026-01-17    3
2026-01-18    2
Name: count, dtype: int64